---
source: src/validation/tests/generic_validation_tests.rs
expression: make_readable(&diagnostics)
---
ImprovementSuggestion { message: "Potential loss of information due to assigning 'DATE_AND_TIME' to variable of type 'USINT'.", range: [SourceRange { range: 135..136 }] }
SyntaxError { message: "Invalid type nature for generic argument. DATE_AND_TIME is no Num.", range: [SourceRange { range: 135..136 }], err_no: type__invalid_nature }
ImprovementSuggestion { message: "Potential loss of information due to assigning 'DATE_AND_TIME' to variable of type 'USINT'.", range: [SourceRange { range: 208..209 }] }
SyntaxError { message: "Invalid type nature for generic argument. DATE_AND_TIME is no Num.", range: [SourceRange { range: 208..209 }], err_no: type__invalid_nature }
ImprovementSuggestion { message: "Potential loss of information due to assigning 'DATE' to variable of type 'USINT'.", range: [SourceRange { range: 276..277 }] }
SyntaxError { message: "Invalid type nature for generic argument. DATE is no Num.", range: [SourceRange { range: 276..277 }], err_no: type__invalid_nature }
ImprovementSuggestion { message: "Potential loss of information due to assigning 'TIME_OF_DAY' to variable of type 'USINT'.", range: [SourceRange { range: 349..350 }] }
SyntaxError { message: "Invalid type nature for generic argument. TIME_OF_DAY is no Num.", range: [SourceRange { range: 349..350 }], err_no: type__invalid_nature }
ImprovementSuggestion { message: "Potential loss of information due to assigning 'TIME_OF_DAY' to variable of type 'USINT'.", range: [SourceRange { range: 417..418 }] }
SyntaxError { message: "Invalid type nature for generic argument. TIME_OF_DAY is no Num.", range: [SourceRange { range: 417..418 }], err_no: type__invalid_nature }

