---
source: src/validation/tests/array_validation_test.rs
expression: res
---
SemanticError { message: "Array __main_arr_1d has size 5, but 6 were provided", range: [SourceRange { range: 67..71 }], err_no: arr__invalid_array_assignment }
SemanticError { message: "Array __main_arr_2d has size 10, but 11 were provided", range: [SourceRange { range: 116..121 }], err_no: arr__invalid_array_assignment }
SemanticError { message: "Array __main_arr_2d_nested has size 10, but 11 were provided", range: [SourceRange { range: 181..186 }], err_no: arr__invalid_array_assignment }
SemanticError { message: "Array __main_arr_3d has size 8, but 9 were provided", range: [SourceRange { range: 237..241 }], err_no: arr__invalid_array_assignment }
SemanticError { message: "Array __main_arr_3d_nested has size 8, but 9 were provided", range: [SourceRange { range: 316..320 }], err_no: arr__invalid_array_assignment }
SemanticError { message: "Array __main_arr_1d has size 5, but 6 were provided", range: [SourceRange { range: 484..488 }], err_no: arr__invalid_array_assignment }
SemanticError { message: "Array __main_arr_2d has size 10, but 11 were provided", range: [SourceRange { range: 503..508 }], err_no: arr__invalid_array_assignment }
SemanticError { message: "Array __main_arr_2d_nested has size 10, but 11 were provided", range: [SourceRange { range: 530..535 }], err_no: arr__invalid_array_assignment }
SemanticError { message: "Array __main_arr_3d has size 8, but 9 were provided", range: [SourceRange { range: 550..554 }], err_no: arr__invalid_array_assignment }
SemanticError { message: "Array __main_arr_3d_nested has size 8, but 9 were provided", range: [SourceRange { range: 576..580 }], err_no: arr__invalid_array_assignment }

