---
source: src/validation/tests/statement_validation_tests.rs
expression: res
---
SyntaxError { message: "Expected a reference for parameter byRefInOut because their type is InOut", range: [SourceRange { range: 589..590 }], err_no: call__invalid_parameter_type }
SyntaxError { message: "Expected a reference for parameter byRefOutput because their type is Output", range: [SourceRange { range: 592..593 }], err_no: call__invalid_parameter_type }
SyntaxError { message: "Expected a reference for parameter byRefInOut because their type is InOut", range: [SourceRange { range: 616..617 }], err_no: call__invalid_parameter_type }
SyntaxError { message: "Expected a reference for parameter byRefOutput because their type is Output", range: [SourceRange { range: 646..647 }], err_no: call__invalid_parameter_type }
SyntaxError { message: "Expected a reference for parameter byRefInOut because their type is InOut", range: [SourceRange { range: 706..707 }], err_no: call__invalid_parameter_type }
SyntaxError { message: "Expected a reference for parameter byRefOutput because their type is Output", range: [SourceRange { range: 709..710 }], err_no: call__invalid_parameter_type }
SyntaxError { message: "Expected a reference for parameter byRefInOut because their type is InOut", range: [SourceRange { range: 733..734 }], err_no: call__invalid_parameter_type }
SyntaxError { message: "Expected a reference for parameter byRefOutput because their type is Output", range: [SourceRange { range: 763..764 }], err_no: call__invalid_parameter_type }

