---
source: src/validation/tests/array_validation_test.rs
expression: res
---
SemanticError { message: "Array __main_arr_init_invalid has a size of 5 but 6 elements were provided", range: [SourceRange { range: 173..191 }], err_no: arr__invalid_array_assignment }
SemanticError { message: "Array arr has a size of 5 but 6 elements were provided", range: [SourceRange { range: 346..364 }], err_no: arr__invalid_array_assignment }
SemanticError { message: "Array arr has a size of 5 but 6 elements were provided", range: [SourceRange { range: 377..393 }], err_no: arr__invalid_array_assignment }

