---
source: src/validation/tests/array_validation_test.rs
expression: res
---
SemanticError { message: "Array __main_arr_a_valid_invalid has a size of 8 but 9 elements were provided", range: [SourceRange { range: 284..311 }], err_no: arr__invalid_array_assignment }
SemanticError { message: "Array __main_arr_b_invalid has a size of 8 but 12 elements were provided", range: [SourceRange { range: 502..559 }], err_no: arr__invalid_array_assignment }
SemanticError { message: "Array arr_a has a size of 8 but 9 elements were provided", range: [SourceRange { range: 771..798 }], err_no: arr__invalid_array_assignment }
SemanticError { message: "Array arr_a has a size of 8 but 9 elements were provided", range: [SourceRange { range: 813..838 }], err_no: arr__invalid_array_assignment }
SemanticError { message: "Array arr_b has a size of 8 but 12 elements were provided", range: [SourceRange { range: 853..927 }], err_no: arr__invalid_array_assignment }

