---
source: src/validation/tests/generic_validation_tests.rs
expression: make_readable(&diagnostics)
---
SyntaxError { message: "Invalid type nature for generic argument. TIME is no Num.", range: [SourceRange { range: 465..473 }], err_no: type__invalid_nature }
SyntaxError { message: "Invalid type nature for generic argument. BYTE is no Num.", range: [SourceRange { range: 475..483 }], err_no: type__invalid_nature }
SyntaxError { message: "Invalid type nature for generic argument. STRING is no Num.", range: [SourceRange { range: 485..492 }], err_no: type__invalid_nature }
SyntaxError { message: "Invalid type nature for generic argument. CHAR is no Num.", range: [SourceRange { range: 494..502 }], err_no: type__invalid_nature }
SyntaxError { message: "Invalid type nature for generic argument. DATE is no Num.", range: [SourceRange { range: 504..512 }], err_no: type__invalid_nature }

